### ISSUE TITLE
Art assets planning

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-platformer-2d#100]
List of assets to produce for the demo

## Art process

If you need a hand for any of the more technical parts of the process, please ask anytime. If there's a task you need to do a lot and think we could automate, in or outside Krita, write it down. If we can, we'll write some code to automate it for you.

### Modular animation

For the character and animated assets, I need each limb to be a separate sprite. You don't need to split every single finger or body part. But e.g. for Robi, I need the thighs and legs to be separate, a Sprite for the torso, the arm, forearm, and the head. You can draw each limb on a single layer, or as a set of layers inside a group depending on how you like to work.

![SuperBoxBot_character_sheet_m](https://user-images.githubusercontent.com/12694995/61460486-1cbb1f00-a96f-11e9-9888-d6b7dcfa93f0.jpg)

### We need to test sprites early on

Before you refine and polish sprites, please export a very rough version of the sprites so that we can integrate them in the game and test them to see that the proportions, colors, contrast, etc. work well during gameplay. A sprite could look beautiful in Krita, but if it does not work in-game, we will have to throw it away. 

### Export and asset pipeline

To export the sprites we have [our own Krita add-on](https://github.com/GDquest/GDquest-art-tools/) (_NB: it should be included in future versions of Krita_). Once you set up your document correctly it will automatically export all the sprites to the right folders. You can draw sprites in different .kra documents and add them as file layers in a document dedicated to export. And you can re-export everything with one click anytime.

### Resolution

The game is going to be 1920 x 1080. You should work at 2x this resolution. E.g. if the final character is `100 x 250` in-game, you should draw it at a size of `~200 x 500`. We'll scale down and sharpen the sprites on export.

Avoid working with a resolution that's not too big, like that:

- Makes the files a lot faster to load and export, especially as you start to have a lot of sprites
- Allows you to use more demanding or slow features in Krita like layer styles and gradient map filters
- Prevents us artists from adding too many details that will not be visible in the game

#### Concept art ####

- [x] Rough concept art for a valley with woods

#### Tile-set ####

- [x] Autotile for the ground (~15-20 tiles)
- [x] 3-5 Tiles for floating platforms
- [x] A few variations for the most used tiles (mainly horizontal ground tile)

#### Background ####

- [x] Large sprites we can use parallax with, e.g. a few mountains, clouds
- [x] Tiling sky texture. We have to discuss this after we validate the concept art, because it might be easier to handle with shaders in the game engine than painting large textures

#### Interactive ####

- [x] Hooking spot: a pole or some device the player can hook onto in the world
- [x] Altar where the player finds and unlocks new powers (hook, enhancements for the hook)
- [x] Checkpoint, place where/from the player can teleport and save the game

### Robi ###

- [x] Body side-3/4 view with split sprites for animation
- [x] Hook
- [ ] Tiling texture for the hook's rope

### Monster ###

- [x] Concept art for two flying enemies based on the game's design

### Various ###

As we still miss some concept art and level design, count a few more concepts and 20 sprites for various props to fill the environment, extra limb drawings for the character, etc.

I'll extend the list once we made some more progress.

**Comment by NathanLovato** [comment]
To work efficiently, do you mind if we have a shared folder on Dropbox?  This way, when you are done working on a set of sprites, I can help you set up the document for export, integrate the sprites in the game, and make small changes directly in a copy of the Krita files to adapt the proportions and what-not for the needs of the game. This will save time for the two of us.

**Comment by Asmo99** [comment]
![background1](https://user-images.githubusercontent.com/52934236/61536377-cb756300-aa34-11e9-9e61-c4cb63d8dd1e.png)
![background2](https://user-images.githubusercontent.com/52934236/61536381-cdd7bd00-aa34-11e9-9b59-3a7b25b3145e.png)
Some concepts for the background

**Comment by NathanLovato** [comment]
For environments, I think paintings like these aren't too useful. A mood board with a collection of reference pictures (photos, paintings from other artists, games, images to show the intended color palette and ambience) followed by some rough thumbnails painted with the in-game view, that you can break down into lists of sprites, are much more efficient when it comes to getting started with visual development for a side-scrolling game.

Something like that (no need to make it tidy):

![Screenshot from 2019-07-19 16-05-20](https://user-images.githubusercontent.com/12694995/61541020-172d0a00-aa3f-11e9-926d-2a4b620a49c3.png)

Followed by rough mockups in the game's view, using the same aspect ratio (16:9). That's because the constraints make it so regular paintings won't translate well into modular game sprites and with the blocky nature of tilesets.

**Comment by NathanLovato** [comment]
Although we align with the idea, especially the upper painting. A bucolic and fairly warm environment that marks the start of the hero's journey 🙂

**Comment by NathanLovato** [comment]
The camera angle is going to be something like that:

![image](https://user-images.githubusercontent.com/12694995/61541500-15b01180-aa40-11e9-9fef-d871c5e3497e.png)

**Comment by Asmo99** [comment]
![moodboard](https://user-images.githubusercontent.com/52934236/61547800-6594d580-aa4c-11e9-8150-ed51b0fc0c42.png)
Here's a quick moodboard where i included two quick sketches (im going to make more detailed ones) for my idea on how the levels would look like.  I had the idea that since it's nature focused, i would only need to make modular sets of painted trees, rocks, lants, etc, wich is rather quick to make. Id like to go with saturated colors, and mostly a complementary/triadic palette.

**Comment by Asmo99** [comment]
![background3](https://user-images.githubusercontent.com/52934236/61550898-03d86980-aa54-11e9-8c7e-38f414cb6272.png)
Rough sketch in 16:9 resolution

**Comment by NathanLovato** [comment]
16:9 isn't the resolution, it doesn't mean you need to use a 1920x1080 canvas: it's just the ratio of the frame. 
Talking about resolution, for rough thumbnails, something like 480x270 would be enough. The resolution isn't important though. I just meant you should keep it small, rough, and move onto actual assets and the actual game view early on.

I like the general idea, although a monocromatic color scheme wouldn't work. It could be useful to work on the character sprite as in a game it'd be common to all environments, and to work on the composition for the environment in response.

**Comment by Asmo99** [comment]
I meant ratio dunno why i wrote resolution.
Should i make more rough thumbnails or do you want me to work on some tiles/assests? If yes what should i start with? I was thinking of the platforms first , like the bare essentials first to see if it fits within the game then work on the more decorative stuff (like trees, plants, rocks, etc)

Also questions about the tiles, do they have a specific resolution? like are they regular texture size (something like 512x512 or 256x256) or do they all have unique sizes?

**Comment by NathanLovato** [comment]
I'll prep a mockup document that I'll put on Dropbox. I think you should start with rough versions of of the character and gameplay assets as the environment is going to support them.

**Comment by Asmo99** [comment]
I'm finally free now, had busy weekend. I started with quick roughs of the Character, the hook and a platform. Tough i'm not sure if you wanted them like just as black shapes to test of they fit first, or very quickly colored pieces. In any case i uploaded both sets individually on Dropbox. Let me know if you need me to change anything or if you want more roughs.
![set1](https://user-images.githubusercontent.com/52934236/61615819-3e662000-ac67-11e9-83b7-8399ec7ac2f4.png)

**Comment by Asmo99** [comment]
![sketch](https://user-images.githubusercontent.com/52934236/61633705-f1e30a80-ac8f-11e9-8022-4b87b7cae9c2.png)

**Comment by Asmo99** [comment]
![anchor point](https://user-images.githubusercontent.com/52934236/61648108-14d0e700-acaf-11e9-9024-5160d1ab3b30.png)
lighter color is where the hook attaches to the asset.
![Checkpoint](https://user-images.githubusercontent.com/52934236/61648111-17334100-acaf-11e9-8431-6d5c604e4fd4.png)
 Note the checkpoint design could also serve as an altar, but in order to make them distinct from altars, checkpoint would have a floating diamond instead of an orb.

**Comment by NathanLovato** [comment]
We're getting to the end of it, so closing the task for now :)
