### ISSUE TITLE
Blockers for final level polish

### ISSUE THREAD

**Issue by DrNeroCF** [GDQuest/godot-platformer-2d#119]
I'll do some more rough level design soon, but before I can do a final level pass, we would need to figure out these things:

- Player movement -
The main thing would be deciding on launching past the hook points, since that changes placement of points and platforms, and opens up a few more ways I can challenge the player (hooking a node from the correct side, aiming at a smaller platform, launching onto a wall and wall jumping), especially for divergent paths.

- Enemies -
How will players interact with enemies?  Attacking with hook, correct?  Will they take advantage of the 360 aiming of the hook, like flying downward at the player as well as enemies that just walk around?  Enemies that take advantage of the hooking mechanic, like a baddie with a hook point above them and a shield in front, player needs to hook over and attack from behind?  Can enemies use hook points to launch at the player?  Would be pretty interesting...  For now I can just leave open areas for enemies, but we'll need to assume that encounters will be interesting enough on their own in an empty level space.

- Collectables -
Will the player be picking up coin type items?  Will there be separate paths to go grab a few coins?

- Blocks / breakables -
Passive objects that the player can attack while moving through levels, like crates, barrels, mario type coin blocks?

- Level structure -
Just need a bit more clarity on the planning, though having real level transitions would help with testing.  Should we have smaller sections within bigger levels?  Levels built for backtracking?  How much exploring should the player be doing?  Or keeping it more straightforward?  Bonus levels that can only be reached in previous levels once upgrades are gotten, that sort of thing.  Basically, should I be planning the minimum layout, or give the player a bit more to explore?

This isn't too urgent, I think the decision that would help the most would be if I should be making optional paths where the player would be collecting coins or discovering optional levels or such.

**Comment by NathanLovato** [comment]
For the needs of the course, I'd say yes for optional paths, and loops or backtracking. To not have just a linear platformer but show some metroidvania-specific features the community requested. Although all in all, the adventure is going to be really short.

I was planning to show a game without collectibles like coins to help focus the viewer's attention on the world design, make it feel like a Metroidvania even though it's short. Use art assets to guide the viewer's eye, and cover the challenge of designing a path and guiding the player without e.g. placing collectibles in a curve. I'd like to have the player explore by themselves - again, to sell the idea of a Metroidvania.

**Comment by DrNeroCF** [comment]
Sounds good.  Upgrades for hidden rooms?  Health upgrades, health replenishment, damage upgrades?

I think I have a better idea for the hook boost mechanic, let's keep it as an upgrade, but just very early in the game (like the morph ball).  I could keep what I have now and put the upgrade at the end, or stay closer to the morph ball and put it right to the left).

I'll just need a way to toggle that upgrade to make a final design for it, but I can make something rough for now to get down movement options that I'm thinking of already.

**Comment by NathanLovato** [comment]
Thanks for your work Brad! Too bad we were delayed and you're busy now. Good luck with the next FPA :)
