### ISSUE TITLE
Integrate the art assets cleanly into the game

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-platformer-2d#167]
Use the exported assets drawn by our artist @Asmo99, but also Krita and the batch export addon to improve the game's visuals in Godot. Some assets may need cleanup, to be resized... Get in touch with me if you need anything there.

I put some assets into the game already, but there are:

1. Some assets missing
2. Some assets don't properly tile

## To add

- [x] Checkpoint
- [x] Hooking point
- [x] Portal
- [ ] The first monsters, the flying fish and shielded monster. Attach the fish/bird-like monster sprite to the Charger monster scene.
- [x] Final sprite for Robi, the main character. Test `robi_shaded.png` to see if it works well. **Do not** integrate the full cutout character yet.

## To refine

Background assets, i.e. the mountains, sky, and cloud.

- [x] The sky could be replaced by a gradient texture in Godot, while the mountains should cleanly tile.
- [x] Ensure the background's parallax works well and the edges of the mountains don't get in the view.

## To review

The background assets need review, especially the ones in the `props` directory won't work well in my opinion. They are not as polished as the other sprites, have a somewhat different style, more textured, and more importantly, their format won't work well for level design. We might need to scrap or redo them.

**Comment by NathanLovato** [comment]
@razcore-art Could you take care of this one?

**Comment by razcore-art** [comment]
Yes, I missed this issue, I'll assign myself to it.
