### ISSUE TITLE
Kill the player when falling too low

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-platformer-2d#173]
Update levels 1 and 2 so the character dies when falling too low. This can work with rectangular areas that the level designer sets by hand.

Is there a way to make something like an infinite area, like a height below which the character will die, regardless of the level's length? Maybe we should have something like that for the cases where the level designer forgets a pit.

**Comment by henriiquecampos** [comment]
> Is there a way to make something like an infinite area, like a height below which the character will die, regardless of the level's length

Yep, the Line2D Collision Shape, it triggers the overlapping on a vector with virtually infinite length. It should do the trick, it's what I often use for "void areas"

Gonna tackle this right the way.
