### ISSUE TITLE
Mouse click events are not working in Game.tscn

### ISSUE THREAD

**Issue by phoenleo** [GDQuest/godot-platformer-2d#178]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
Mouse events are not passed into `_unhandled_input()` function in **_Hook_** state.
Both left click and right click events are not passed to `_unhandled_input()` thus making the game unplayable due to _**hook** input event_ is never processed

**What is the expected behavior?**
Mouse left click should trigger _**hook** input event_ and **Player** can fire the _hook_

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
1. Clone the project from **master** branch with commit ID **ad33cf98e08e3afdda85526ceef27ce3af72b9f3**
2. Play the Game (**F5**) 
3. Player cannot fire Hook using _mouse left click_ in **Game.tscn**
4. If Player add the hook action to another input (e.g. **R** key), the hook can be fired using the new key (**R** key)
5. Hook can be fired using _mouse left click_  in **Player.tscn** and **Hook.tscn**

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information** 
Tested on:
- Windows 10
- Godot 3.1 and Godot 3.2

**Comment by NathanLovato** [comment]
Closed by #179
