### ISSUE TITLE
The Player falls endlessly

### ISSUE THREAD

**Issue by martinbelcic** [GDQuest/godot-platformer-2d#187]
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

**What is the current behavior?**
If the player falls in an area where there is no ground (e.g. at the end of level 1) he will fall forever without dying.

**What is the expected behavior?**
The player should die.

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 
1. Start the game.
2. Play until you reach the end of the level.
3. Miss a hook and fall in that area.

**Comment by NathanLovato** [comment]
Yes, it's not implemented yet.

**Comment by henriiquecampos** [comment]
Should that be fixed at https://github.com/GDQuest/godot-platformer-2d/pull/177 ?

**Comment by NathanLovato** [comment]
The killing line was missing from the level scenes, so the player would fall indefinitely. This is now fixed. Thanks for mentioning that, I had forgotten about this node!
