### ISSUE TITLE
Concept art for the game character and environment

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-platformer-2d#96]
This task is about developing the visuals of the game with thumbnails and other rough paintings.

As the scope of the game is small and it is 2D, the goal is to do **visual development for the final assets that will be in the game**. We need roughs of how the **actual game and characters** would look like more so than e.g. illustrations of the world.

## About the game

Here’s a short video recording of the current alpha: https://www.dropbox.com/s/fjck8l2mwpflgki/2019-07-15-hook-pre-alpha.mp4?dl=0

You can find game design information in:

1. The repository’s [readme](https://github.com/GDquest/godot-metroidvania-2d#2d-metroidvania-godot-course-demo-project)
1. The [game concept](https://github.com/GDquest/godot-metroidvania-2d/blob/master/GAME_CONCEPT.org)

## To do

To start with, we need concepts and roughs for, from the most to the least important:

2. Main character: Robi the robot
3. Robi’s hook, the player’s main tool and the game’s core mechanic
4. The environment. It has yet to be decided, more on that below
5. Hooking points, the objects on which Robi can hook
6. An altar or a place where Robi will find the hook, and upgrades in the game

## Technical constraints

If we ever animate the characters, we will use modular animation (e.g. Rayman legends):

![image](https://user-images.githubusercontent.com/12694995/61217165-67d6f700-a70f-11e9-8689-781b5fa47f3f.png)

You don't need to bother about cutting the sprite but the characters and monsters you'll design should take this into account. E.g. it doesn't work too well with human anatomy, and joints like the crotch can be an issue. The characters in Breath of Fire 6 have large belts or elements to hide issues in the pelvic area:

![image](https://user-images.githubusercontent.com/12694995/61217350-c4d2ad00-a70f-11e9-966f-b7fb5d90bde9.png)

Also, the playable character is small on screen, so there is little room to give it realistic proportions: it should be two to four heads tall. The designs should have these technical constraints in mind.

![image](https://user-images.githubusercontent.com/12694995/61217522-272bad80-a710-11e9-9ffe-ddfa58bd6c18.png)

We use a tilemap to design the levels. The tiles are small. You are welcome to add sprites that are organic to place in the foreground or in the background, but the main path is going to be mainly horizontal and vertical.

The game plays as a side scroller, but the camera angle can be slightly top down to give it a bit more depth. Example from Monster Boy:

![monster-boy resized](https://user-images.githubusercontent.com/12694995/61218111-8e962d00-a711-11e9-8429-36b0369394f6.jpg)

## Art style

The characters and other foreground elements have to pop over the background. I am not set on anything at this point. A more painterly or a more cel shaded/anime style can both work all the characters and other interactive sprites.

The main constraints here are:

1. The visuals should be contrasted and vibrant
2. I don't want a dark environment

**Comment by NathanLovato** [comment]
That's some information to get the discussion started. Could you please tell me what other information you need to get the job done?

Some information about the character, the game's background, a synopsis...

**Comment by NathanLovato** [comment]
Here are two versions of Robi, one in 3d from Fernando, and the sprites I made for our OpenRPG demo/framework for Godot

![robi](https://user-images.githubusercontent.com/12694995/61241371-aab2c200-a743-11e9-825f-5b508e4ae14c.jpg)

**Comment by Asmo99** [comment]
Ok, so i went trough all the documents and from my understanding the first task would be to start concepts for the Main character Robbi. Things like the design, how he moves, interact, etc. I already have some ideas but i want some clarifications on the Character design part: Do i need to create a specific design for him (with the inspiration of previous designs) or instead reuse another one from a previous game?

**Comment by NathanLovato** [comment]
Robi has this cylindrical head that looks a bit like a portable speaker, and these characteristic eyes. You mostly have to keep this. The design is fairly free otherwise. In this game, it needs a tool to hook, and this tool should be prominent as it's part of the core gameplay.

I couldn't find a lot of time to work on it but here's an example. Gave it a large arm, an antenna to help with its facial expression, and wings for the silhouette:

![robi-concept](https://user-images.githubusercontent.com/12694995/61278326-4bd96100-a7b4-11e9-8227-26a2177502fc.jpg)

**Comment by Asmo99** [comment]
![MC_designbatch 1](https://user-images.githubusercontent.com/52934236/61287483-40dafc80-a7c5-11e9-8bba-79cdb69f41c9.png)
Here's a first batch of designs :) 1 and 2 are the same, just with different proportions. With the first 3 i went the an "adventurer look" wich imo fits with the hook thing and the gameplay. There's also 4 wich is closer to the 2 other designs from previous games. 5 Is some weird idea i had, like i had in mind that his limbs are connected by some ethereal like matter/energy, and the hook would be kind of the same. But anyway feedback is very appreciated, let me know if there's a particular design you like and i'll refine it, otherwise I'll continue sketching ideas. I like 3 and 1 the best personally

**Comment by Asmo99** [comment]
One thing to note im more experimenting with themes and overall shape, proportions aren't whats important here (yet)

**Comment by NathanLovato** [comment]
I like the adventurer style as well, 3 in particular. I think it'd be useful to start to think about who the character is, what's his purpose, the world he's in.

At least gameplay-wise, considering he's using a hook, I think it's best that it doesn't look like it's an advanced robot with futuristic technology.

I'll let you work a bit more in that direction, and I'll start to write about the game world based on your sketches if you don't mind :)

**Comment by Asmo99** [comment]
Go ahead! I'll start making some variations for design 3 and refining it overall. Im also going to look for a palette

**Comment by Asmo99** [comment]
![MC_design2](https://user-images.githubusercontent.com/52934236/61297660-f5cce380-a7dc-11e9-9aff-2600f33e992e.png)
Some scribbled ideas, tought im not done yet i want to experiment more

**Comment by Asmo99** [comment]
![MC_design3](https://user-images.githubusercontent.com/52934236/61307175-279a7600-a7ee-11e9-9260-9471d3f70236.png)
Another small set of designs

**Comment by NathanLovato** [comment]
Could you work on the hook next? I like where the design is going. The character seems to have some bird-like features. It opens to some interesting possibilities for world development, among other things.

**Comment by Asmo99** [comment]
Ok! I have alot of ideas for the hook :)

**Comment by NathanLovato** [comment]
Also, do you have an idea of how you could turn this into a 2-3-4 heads tall design? as in-game, the character is really small. It's the blue square:

![Screenshot from 2019-07-16 17-45-19](https://user-images.githubusercontent.com/12694995/61308889-81506f80-a7f1-11e9-9d04-5db3e5807706.png)

It'd be nice if the face could still read, but more importantly, the hook may hide some of the character as it has to be clear for gameplay purposes.

**Comment by Asmo99** [comment]
Shrinking the proportions could fix that. A more chibi esque style could fit and since the design are made of strong shapes it should adapt with no problem. Colors will also play in readability of the character. Making the Character and the hook opposite colors could help (ex the character's is white with orange clothes and to contrast the hook has blue tones).

**Comment by Asmo99** [comment]
![hook1](https://user-images.githubusercontent.com/52934236/61313704-4e12de00-a7fb-11e9-9dda-c35ca051d694.png)
Here's a first set of designs :D

**Comment by Asmo99** [comment]
![hook2](https://user-images.githubusercontent.com/52934236/61322102-3f352700-a80d-11e9-9dfe-ce1c2f3157d7.png)
small second set with more fisher hook like shapes

**Comment by Asmo99** [comment]
![MC_design4](https://user-images.githubusercontent.com/52934236/61354502-9a4d3500-a872-11e9-98d8-4aa0d42b416e.png)
I forgot to post this yesterday but here's a sketch where i tried more chibi-like proportions

**Comment by NathanLovato** [comment]
I thought about the game world yesterday and who the character could be, to help constraint and funnel down the design work, that could otherwise go in any direction.

As Robi is a robot and you have a bit of a bird-like design for him, which I really like, I was thinking that the character could be a robot who aspires to fly in a society that lives on the ground and hasn’t found a way to fly yet. These robots use mechanical hooks and rails to travel around and transport goods, and that’s why you’d have hooking scattered around the game world.

Robi, as a kid, always looked up to the mysterious sky,  one that nobody seemed to have explored.  one day, he stumbles on an old book that portrays beings similar to his kind, but with wings. This inspires him to become an adventurer, to go on a quest to find these wings, and to explore beyond what every other robot has ever seen: to go high up in the sky, where there is nothing to hook onto.

As a result, he's an adventurer driven by his curiosity and an urge to push boundaries.

**Comment by NathanLovato** [comment]
Regarding the hook, I'm fond of number 4, that looks like it can latch onto a pole, work as a blade, and plant into wooden surfaces. This kind of design would work well for all the gameplay needs we might have.

**Comment by NathanLovato** [comment]
I also think 7, 9, and 10 could work. I do like some others like the hand, but it's too organic. It'd be hard to animate on the one hand, and I feel it wouldn't fit as well as the others with the character's design. Good work so far. 🙂

**Comment by Asmo99** [comment]
I like that bit of lore, it's interesting.
Best hook in my opinion is 4 since it has a strong shape thus more readability.
I think i should now start with colors next, both for Robbi and the Hook. Im going to refine the hook a little bit first tho

**Comment by NathanLovato** [comment]
Great :)
As you're making good progress, soon enough, the next part would be the environment. I haven't taken the time to think about where the characters live and what the environment for the demo should be, which should be the starting point to design them.

There is only going to be one environment for the demo, and only a few levels or frames to play through. I'd like the environment to be vibrant, lively, and visually contrasted.

I'm thinking of the area surrounding a small village in the countryside, in a valley. this would give us rocks, possibly mountains in the background, a path made of dirt, grass, the ability to have trees and some woods... as well as houses and robot-made devices.

Any ideas or suggestions? I'll try to come up with a coherent base background before you get to that.

**Comment by Asmo99** [comment]
It kinda reminds me of Pascal's village in Nier automata 
![image](https://user-images.githubusercontent.com/52934236/61356871-822be480-a877-11e9-9da8-1c5476a3d8e7.png)

**Comment by Asmo99** [comment]
I've been thinking a little bit for the style that i want to use for the environment, I really like the style used for Aion's early concept art, with watercolor like colors and a oil paint like style of rendering. Aion is really focused on the sky (because of the game's flying mechanics) So this is a potential directions i could go 
![image](https://user-images.githubusercontent.com/52934236/61364758-bfe43980-a886-11e9-9d51-68d08f52daaa.png)
![image](https://user-images.githubusercontent.com/52934236/61364784-c83c7480-a886-11e9-9feb-ae9655c8389d.png)
I think i will simplify it tho, so it's more adaptable to the tile system used for the game.

**Comment by NathanLovato** [comment]
The tiles are only going to be for the platforms the character walks on. The far background could use a different style, or at least a different composition: washed out tones, lower contrast...

In any case, for each asset, you should send us a rough so we can test the composition and look in-game, have a solid setup for export, and only then iterate on each sprite to refine and polish it.

E.g. here are the initial rough and refined version of monsters in Pankapu:

![image](https://user-images.githubusercontent.com/12694995/61461944-15494500-a972-11e9-9e95-f4364a1e787e.png)

The roughs both work as concept art and can be tested in-game, even though they're already pretty clean in this case.

**Comment by Asmo99** [comment]
![palette1](https://user-images.githubusercontent.com/52934236/61517912-a539ce00-aa08-11e9-8af0-fcea15ae1b73.png)
Here's a set of diferent palettes to test, both Robbbi and the hook share colors but i made it so they're also contrasting each other. Let me know wich one looks best. Im also going to start working on the environment concept art.

**Comment by NathanLovato** [comment]
This is done since a while ago, closing the task
